version: '3'

services:
    app:
        container_name: mvc-php-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8888:80
        networks:
            - localnet

networks:
    localnet:
        driver: 'bridge'