version: '3'

services:
    app:
        container_name: php-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8888:80
        env_file:
            - ./.env
        networks:
            - localnet
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql-app
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - localnet
        env_file:
            - ./.env

volumes:
    dbdata:
        driver: 'local'

networks:
    localnet:
        driver: 'bridge'